-- Migration 017: Add cover source tracking
-- Adds cover_source column to track how covers were obtained
-- Creates cover_generation_jobs table for async job tracking

-- Add cover_source column to texts table
ALTER TABLE texts 
ADD COLUMN IF NOT EXISTS cover_source TEXT 
CHECK (cover_source IN ('scraped', 'ai-generated', 'manual', NULL));

-- Add comment for documentation
COMMENT ON COLUMN texts.cover_source IS 'Source of the cover image: scraped from APIs, ai-generated by Nano Banana, manual upload, or NULL';

-- Add index for filtering by source (useful for analytics)
CREATE INDEX IF NOT EXISTS idx_texts_cover_source ON texts(cover_source);

-- Create cover generation jobs table for async tracking
-- Useful for monitoring AI generation progress and debugging
CREATE TABLE IF NOT EXISTS cover_generation_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  text_id UUID NOT NULL REFERENCES texts(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed')) DEFAULT 'pending',
  source TEXT, -- Which API/service was used (e.g., 'nano-banana', 'open-library')
  result_url TEXT, -- URL of the generated/scraped cover
  error TEXT, -- Error message if failed
  credits_used INTEGER DEFAULT 0, -- For AI generation cost tracking
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add table comment
COMMENT ON TABLE cover_generation_jobs IS 'Tracks async book cover generation/scraping jobs';

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_cover_jobs_text_id ON cover_generation_jobs(text_id);
CREATE INDEX IF NOT EXISTS idx_cover_jobs_status ON cover_generation_jobs(status);
CREATE INDEX IF NOT EXISTS idx_cover_jobs_created_at ON cover_generation_jobs(created_at DESC);

-- RLS policies for cover_generation_jobs (admin only)
ALTER TABLE cover_generation_jobs ENABLE ROW LEVEL SECURITY;

-- Admins can view all jobs
CREATE POLICY "Admins can view cover jobs"
  ON cover_generation_jobs
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  );

-- Admins can insert jobs
CREATE POLICY "Admins can create cover jobs"
  ON cover_generation_jobs
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  );

-- Admins can update jobs
CREATE POLICY "Admins can update cover jobs"
  ON cover_generation_jobs
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  );

