-- CSV → texts table backfill, generated by scripts/audit-csv-vs-db.mjs
-- 2026-05-09T01:38:16.033Z
-- 87 rows. Review before running. Wrap in BEGIN/COMMIT to be safe.

BEGIN;
-- T001  The Kybalion
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/eso/kyb/index.htm' WHERE id = '0b80316f-3702-4a72-b415-0f505217ecac';
-- T002  On the Origin of Species
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1228' WHERE id = '8165b1a3-e46f-47e1-8eeb-d27beab78bb6';
-- T003  The Interpretation of Dreams
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/56657' WHERE id = '6f84145a-1623-42ac-a750-03e1edeb55c0';
-- T004  Meditations
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/2680' WHERE id = 'fc5471cd-2644-4b35-b184-94b6ac659d6e';
-- T005  The Bhagavad Gita
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/2388' WHERE id = '4807b1ee-02af-4250-9247-e65b0f2f7602';
-- T007  The Golden Bough
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3623' WHERE id = '9289146c-1348-41b4-b1f5-725e2961270c';
-- T009  The Republic
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1497' WHERE id = 'e0f74b88-c6d3-48aa-86ca-7304b19c28c1';
-- T010  The Secret Teachings of All Ages
UPDATE texts SET source_url = 'https://www.sacred-texts.com/eso/sta/index.htm' WHERE id = 'ef9fb191-2387-4cee-b48f-f10848be3035';
-- T012  The Varieties of Religious Experience
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/621' WHERE id = '7f708035-2317-4e74-94a5-bb9874af2fe7';
-- T013  The Emerald Tablet
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/alc/emerald.htm', year = 150 WHERE id = '5da97a09-e741-4eb2-91e1-5bd7e790ca6d';
-- T014  Cosmic Consciousness
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/8819' WHERE id = 'a97851a8-35f6-4f3d-a009-2b2b09d89ec2';
-- T015  The Confessions
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3296' WHERE id = 'a4d9c210-571f-4112-ae9f-18a237549d0e';
-- T016  The Upanishads
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3283' WHERE id = '540bc6c0-3540-4382-a910-559a4a3a63b7';
-- T019  Relativity: The Special and General Theory
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/5001' WHERE id = 'b829fc09-40c9-48fa-aba2-94fa4e5debac';
-- T020  The Book of the Sacred Magic of Abramelin
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/grim/abr/index.htm' WHERE id = '3619a146-aa4b-47d3-919f-68f53e057a33';
-- T021  Transcendental Magic
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/eso/tm/index.htm' WHERE id = '9c95ee41-c716-4cc9-b9e3-582109054f9a';
-- T022  The Descent of Man
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/2300' WHERE id = '2d985f42-9485-4ad5-9816-ad55e19f7db8';
-- T023  Psychology of the Unconscious
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/47942' WHERE id = '57c60b58-f02b-4066-a6cb-4bd83ee70ab7';
-- T025  Beyond Good and Evil
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/4363' WHERE id = '0858faec-d3af-45fd-a7b1-7c81685af59e';
-- T026  The Dhammapada
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/2017' WHERE id = '37c63950-f8ca-4279-bc1b-da63c2ba0ae4';
-- T027  Sepher Yetzirah
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/jud/yetzirah.htm' WHERE id = 'f44ae795-d27a-4e9a-9312-c67eeb6ace19';
-- T028  The Voyage of the Beagle
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/944' WHERE id = '1ef61ade-d26e-4b07-ae38-0181b956e9ea';
-- T029  The Enneads
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/55317' WHERE id = 'f5918c32-74fb-4415-aa72-6d8adaaffe3b';
-- T030  The Analects
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3330' WHERE id = '89e2960b-9045-45c0-a12a-e0560bdd8078';
-- T031  The Kabbalah Unveiled
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/jud/tku/index.htm' WHERE id = 'eaf89b8a-7d12-4632-8fa4-b02b658507c7';
-- T032  Tetrabiblos
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/astro/ptb/index.htm' WHERE id = 'eb3efa73-be54-4dd7-9dfc-4c6a68903ed4';
-- T033  The Ego and the Id
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/52694' WHERE id = '20d1cd44-e70e-4e2f-8ea1-69a53915fad3';
-- T035  Myths and Legends of Ancient Greece and Rome
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/22381' WHERE id = '0c1ed233-97ff-490f-9d1b-06763858966e';
-- T036  The Pictorial Key to the Tarot
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/tarot/pkt/index.htm' WHERE id = '7f15fd59-b9bc-430d-a05a-8587f226b82f';
-- T038  The Life of St. Teresa of Jesus, of the Order of Our Lady of Carmel
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/chr/teresa/lsa/index.htm' WHERE id = 'd8e4b4a3-c1fa-4adb-97aa-93b75ff842e2';
-- T039  The Interior Castle
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/8120' WHERE id = '35ab49c4-85bc-42f9-b24f-729c0642c162';
-- T040  Self-Reliance and Other Essays
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/16643' WHERE id = '2efa3e18-200c-4cb4-a930-1a4a907512bb';
-- T041  The Art of War
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/132' WHERE id = 'df99197e-a98d-40c7-9143-b644b6d900dc';
-- T042  I Ching
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/ich/index.htm' WHERE id = '8c72e0da-ed2c-433e-9566-5c1907e5ffdc';
-- T044  The Tarot of the Bohemians
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/tarot/tob/index.htm' WHERE id = '2c893ab4-8f88-48ba-ae82-4bde0242660d';
-- T046  Christian Astrology
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/astro/ca/index.htm' WHERE id = 'ab1e86d5-2259-4284-932f-485fadc9ccfe';
-- T047  The Symposium
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1600' WHERE id = '70b7b64c-cb0d-42ee-ba3a-b982b4293134';
-- T048  The Discourses
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/871' WHERE id = '14703f18-2df7-4063-9aa0-bc8b5236d4eb';
-- T049  Ethics
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3800' WHERE id = 'd39c2ff5-e65c-4d5b-bb6f-26b65b5779da';
-- T050  The Problems of Philosophy
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/5827' WHERE id = '01c7a32b-f820-48a5-8ea7-c3066c490075';
-- T053  The Metaphysics
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/54448' WHERE id = '67f778e7-101d-43ff-84ce-16f109a11f7a';
-- T054  Beyond the Pleasure Principle
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/44565' WHERE id = '1e4ae875-08b2-4e2e-9b9e-6e7b678d1088';
-- T055  The Gay Science
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/52914' WHERE id = '4ad980ac-b103-4d14-ae90-9f4e4f456520';
-- T056  The Nature of the Physical World
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/48934' WHERE id = '8b27d017-83b4-4fdb-bf1e-b29d146d837b';
-- T057  Man's Place in Nature
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/2931' WHERE id = 'de503717-d931-446d-b59d-c11dd7758cef';
-- T058  The Divine Pymander
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/eso/pym/index.htm' WHERE id = '933af65d-dc4b-47ba-99ba-046df87dffc7';
-- T059  The Yoga Sutras of Patanjali
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/hin/yogasutr.htm' WHERE id = '9ae8caf8-b798-494b-9d45-8d43ff424994';
-- T060  Mysticism
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/18428' WHERE id = '2acad0f9-e8bc-4625-ab00-ac1ebae98f40';
-- T061  The Art of Worldly Wisdom
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/5690', year = 1647 WHERE id = '8fecdcd1-9ff3-4de9-a07c-42094b97299d';
-- T062  Bulfinch's Mythology
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/4928' WHERE id = '8ebc6e55-52fe-4c39-ade0-98d993646292';
-- T063  The Age of Fable
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/3327' WHERE id = '640fe896-5f7f-48e4-ac42-10755aa64fba';
-- T065  Human Nature and Conduct
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/41386' WHERE id = '303f1c6d-bf9a-4e3f-8e74-40da7a4cd4b5';
-- T066  The Principles of Light and Color
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/eso/ihas/index.htm' WHERE id = '9dfee305-4e2d-43fc-b41d-701b8c2ebe2f';
-- T067  The Tibetan Book of the Dead
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/bud/tib/index.htm', year = 800 WHERE id = '9ebce8df-769a-4a2f-80ef-175c34f3ecef';
-- T068  The Gospel of Buddha
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/48361' WHERE id = '1f8f30fa-6d9c-43ec-aa4a-856962142243';
-- T069  The Conference of the Birds
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/28688' WHERE id = '85e66e1c-2180-4186-a3fb-190a622a16b1';
-- T070  Totem and Taboo
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/41214' WHERE id = '296ea622-5e48-4e62-8cd3-87c3e50d13d7';
-- T072  The Cloud of Unknowing
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/9347' WHERE id = '164a881a-b150-4b12-9448-4839feb491a0';
-- T073  The Imitation of Christ
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1653' WHERE id = '38dcff17-d5fc-4e3f-974b-5cf942e768b0';
-- T074  Magic and Religion
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/37811' WHERE id = 'ed2a8d6e-48f0-41c3-993f-1e2378c582e3';
-- T076  The Masnavi Book 1
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/isl/masnavi/index.htm' WHERE id = '268f0e61-f779-4645-8c91-103a10d4e818';
-- T077  The Alchemy of Happiness
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/48206', year = 1105 WHERE id = 'f3848379-29ca-488b-aeae-5749774b2e84';
-- T078  The Mystics of Islam
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/45166', year = 1914 WHERE id = 'f8f30d3e-7a36-433a-b1db-018278a194d3';
-- T080  The Mechanism of the Heavens
UPDATE texts SET license = 'public-domain', source_url = 'https://archive.org/details/mechanismofheave00some', year = 1831 WHERE id = 'cbe1dd9a-dc28-4f71-9438-d4d0ae962d82';
-- T081  Science and the Modern World
UPDATE texts SET license = 'public-domain', source_url = 'https://archive.org/details/sciencemodernwor00whit' WHERE id = '7e0b3456-ecac-4f85-9f54-7e00b6d0b0c6';
-- T082  The Divine Proportion
UPDATE texts SET license = 'public-domain', source_url = 'https://archive.org/details/divinaproportion00paci' WHERE id = 'f0b046c0-bbaf-4dc0-8b18-ec901ffaddc9';
-- T083  A Treatise on the Circle and the Sphere
UPDATE texts SET license = 'public-domain', source_url = 'https://archive.org/details/treatiseoncircle00cooluoft' WHERE id = '108de633-a898-46e6-9d9e-21dd6ba23688';
-- T085  Jewish Magic and Superstition
UPDATE texts SET source_url = 'https://www.sacred-texts.com/jud/jms/index.htm' WHERE id = '5cd816dd-3c75-4870-9f9e-92324d809b83';
-- T086  Prolegomena to Any Future Metaphysics
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/52821' WHERE id = 'f497cf8b-eb52-4940-9327-d329c04ac4b4';
-- T088  An Enquiry Concerning Human Understanding
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/9662' WHERE id = '73bedaa6-f6fc-4e30-a7ae-1596b11cbcce';
-- T089  The Apology
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1656', year = -399 WHERE id = '6168346c-2af1-483d-b325-304ab18eb39c';
-- T090  Phaedo
UPDATE texts SET license = 'public-domain', source_url = 'https://www.gutenberg.org/ebooks/1658' WHERE id = 'e664a4a5-bd02-4e84-8d17-1b500d4bab3c';
-- T093  The Book of Ceremonial Magic
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/grim/bcm/index.htm' WHERE id = '13757cfd-ffe7-4270-947d-f8594dd13270';
-- T094  The Rosicrucians
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/sro/rhr/index.htm' WHERE id = '53a2c79f-7787-4bb6-a6d2-8aa9df0528b9';
-- T095  The Comte de Gabalis
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/eso/cdg/index.htm' WHERE id = '51cc0d9a-3dbf-4c9b-aaa8-401fc8456ca1';
-- T096  The Practice of Magical Evocation
UPDATE texts SET source_url = 'https://archive.org/details/practiceofmagica00bard', year = 1956 WHERE id = '0682fa94-01d3-4e0c-aec2-6fdf341a5c0b';
-- T097  The Science of Breath
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/hin/sob/index.htm' WHERE id = '8050a350-184d-43da-941c-89e2825b1cb1';
-- T098  Light on the Path
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/the/lop/index.htm' WHERE id = 'd21083f5-8109-4c49-93d6-5b741120fc9e';
-- T099  The Voice of the Silence
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/the/vos/index.htm' WHERE id = 'd64cf893-eafc-437b-8be9-d70f38cdaf3d';
-- T100  The Gateless Gate
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/bud/zen/mumonkan.htm' WHERE id = 'f775eea8-78bf-497f-9c5f-db03da6ed0d0';
-- T101  The Mathematicall Praeface to Elements of Geometrie of Euclid of Megara
UPDATE texts SET license = 'public-domain' WHERE id = '5d610288-1934-4445-850c-8b81fca12c5d';
-- T103  Pistis Sophia
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/chr/ps/index.htm' WHERE id = '9e18756f-b1c7-4cee-be72-b0c0d74b8c11';
-- T105  Initiation, Human and Solar
UPDATE texts SET license = 'public-domain', source_url = 'https://www.lucistrust.org/online_books/initiation_human_and_solar' WHERE id = '8fb67702-22d4-4dcd-bbc6-1bd4372e7006';
-- T106  The Real History of the Rosicrucians
UPDATE texts SET license = 'public-domain', source_url = 'https://www.sacred-texts.com/sro/rhr/index.htm' WHERE id = 'f07b286c-61b3-401e-88d1-956c4bc30d03';
-- T107  The Quran (Pickthall translation)
UPDATE texts SET source_url = 'https://sacred-texts.com/isl/pick/' WHERE id = '8e4adbf6-8eb8-453c-8a1d-ea292af53a55';
-- T110  The Bezels of Wisdom (Fusus al-Hikam)
UPDATE texts SET license = 'public-domain', source_url = 'https://archive.org/', year = 1230 WHERE id = 'a56ced42-cf2d-4037-9d54-86a9d5954990';
-- T112  The Incoherence of the Incoherence
UPDATE texts SET source_url = 'https://archive.org/', year = 1180 WHERE id = 'd18d0031-e240-4796-823c-80040abc7ee4';

-- COMMIT;  -- uncomment to apply
ROLLBACK;