-- Curator note draft workflow
-- Lets AI-generated rewrites be staged and reviewed in admin before
-- promoting to the live curator_note shown on library cards.

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS curator_note_draft TEXT;

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS long_summary_draft TEXT;

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS curator_note_status TEXT NOT NULL DEFAULT 'live';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'texts_curator_note_status_check'
  ) THEN
    ALTER TABLE texts
      ADD CONSTRAINT texts_curator_note_status_check
      CHECK (curator_note_status IN ('live', 'draft_pending', 'draft_rejected'));
  END IF;
END $$;

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS related_texts JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS curator_note_reviewed_at TIMESTAMPTZ;

ALTER TABLE texts
  ADD COLUMN IF NOT EXISTS curator_note_reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS texts_curator_note_status_draft_idx
  ON texts (curator_note_status)
  WHERE curator_note_status = 'draft_pending';

COMMENT ON COLUMN texts.curator_note_draft IS 'AI-generated draft curator note; never shown to users. Promoted into curator_note on approval.';
COMMENT ON COLUMN texts.long_summary_draft IS 'AI-generated draft long summary; never shown to users. Promoted into long_summary on approval.';
COMMENT ON COLUMN texts.curator_note_status IS 'live | draft_pending | draft_rejected — controls the admin review queue.';
COMMENT ON COLUMN texts.related_texts IS 'In-library cross-references generated by the rewrite. Array of { id, title, resonance } objects.';
