-- Inquiries contribute evidence to the knowledge map independently of course imports.
-- Private records are accessed through authenticated curator routes. Public routes
-- project only published claims and the entities they reference.
create table public.research_inquiries (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id),
  title text not null check (length(title) between 1 and 180),
  question text not null default '',
  notes text not null default '',
  revision integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.research_entities (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(name) between 1 and 160),
  kind text not null check (kind in ('concept','person','work','tradition','artifact','symbol')),
  definition text not null default '',
  correspondence_id uuid unique references public.correspondences(id),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
create unique index research_entity_identity on public.research_entities(kind, lower(trim(name)));

create table public.research_findings (
  id uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references public.research_inquiries(id) on delete cascade,
  title text not null check (length(title) between 1 and 180),
  claim text not null default '',
  note text not null default '',
  source_kind text not null check (source_kind in ('library','external','ai','correspondence','note')),
  source_title text not null default '',
  source_url text not null default '',
  source_locator text not null default '',
  excerpt text not null default '',
  text_id uuid references public.texts(id),
  chunk_id uuid references public.text_chunks(id),
  provenance jsonb not null default '{}',
  context text not null default '',
  evidence_class text not null default 'direct_statement' check (evidence_class in
    ('direct_statement','documented_history','tradition_attestation','scholarly_interpretation','personal_interpretation')),
  source_entity_id uuid references public.research_entities(id),
  target_entity_id uuid references public.research_entities(id),
  predicate text not null default 'associated_with' check (predicate in
    ('defines','depicts','explores','compares_with','corresponds_to','historically_connected_to','influenced_by','contrasts_with','associated_with')),
  status text not null default 'draft' check (status in ('draft','reviewed','published')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  published_at timestamptz,
  revision integer not null default 1,
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (source_entity_id is null or target_entity_id is null or source_entity_id <> target_entity_id),
  check (status = 'draft' or (
    source_kind in ('library','external','correspondence') and
    length(trim(claim)) > 0 and length(trim(excerpt)) > 0 and
    length(trim(source_title)) > 0 and length(trim(source_locator)) > 0 and
    length(trim(context)) > 0 and
    (source_kind <> 'external' or source_url ~ '^https?://') and
    (source_kind <> 'library' or text_id is not null) and
    source_entity_id is not null and target_entity_id is not null and
    reviewed_by is not null and reviewed_at is not null
  )),
  check ((status = 'published') = (published_at is not null))
);
create index research_inquiries_owner on public.research_inquiries(owner_id, updated_at desc);
create index research_findings_inquiry on public.research_findings(inquiry_id, sort_order);
create index research_findings_published on public.research_findings(published_at desc) where status = 'published';

alter table public.research_inquiries enable row level security;
alter table public.research_entities enable row level security;
alter table public.research_findings enable row level security;
revoke all on public.research_inquiries, public.research_entities, public.research_findings from anon, authenticated;
grant all on public.research_inquiries, public.research_entities, public.research_findings to service_role;
grant usage, select on sequence public.research_findings_sort_order_seq to service_role;

-- Lock and compare revisions so a review can never publish a stale edit.
create function public.transition_research_finding(
  p_id uuid, p_owner uuid, p_revision integer, p_action text
) returns public.research_findings
language plpgsql security invoker set search_path = public, pg_temp as $$
declare f public.research_findings;
begin
  if not exists (select 1 from public.users where id = p_owner and role = 'admin') then
    raise exception 'Curator access required' using errcode = '42501';
  end if;
  select rf.* into f from public.research_findings rf
    join public.research_inquiries ri on ri.id = rf.inquiry_id
    where rf.id = p_id and ri.owner_id = p_owner for update of rf;
  if not found then raise exception 'Finding not found' using errcode = 'P0002'; end if;
  if f.revision <> p_revision then raise exception 'Finding changed; reload before continuing' using errcode = '40001'; end if;
  if p_action = 'review' and f.status = 'draft' then
    update public.research_findings set status = 'reviewed', reviewed_by = p_owner,
      reviewed_at = now(), revision = revision + 1, updated_at = now() where id = p_id returning * into f;
  elsif p_action = 'publish' and f.status = 'reviewed' then
    update public.research_findings set status = 'published', published_at = now(),
      revision = revision + 1, updated_at = now() where id = p_id returning * into f;
  elsif p_action = 'draft' and f.status in ('reviewed','published') then
    update public.research_findings set status = 'draft', reviewed_by = null, reviewed_at = null,
      published_at = null, revision = revision + 1, updated_at = now() where id = p_id returning * into f;
  else raise exception 'Invalid review transition' using errcode = '22023';
  end if;
  return f;
end $$;
revoke all on function public.transition_research_finding(uuid,uuid,integer,text) from public, anon, authenticated;
grant execute on function public.transition_research_finding(uuid,uuid,integer,text) to service_role;

create function public.move_research_finding(p_id uuid, p_owner uuid, p_direction text)
returns void language plpgsql security invoker set search_path = public, pg_temp as $$
declare f public.research_findings; neighbor public.research_findings;
begin
  if p_direction not in ('up','down') then raise exception 'Invalid direction'; end if;
  if not exists (select 1 from public.users where id = p_owner and role = 'admin') then
    raise exception 'Curator access required' using errcode = '42501';
  end if;
  -- Serialize ordering per inquiry.
  perform 1 from public.research_inquiries ri join public.research_findings rf on rf.inquiry_id = ri.id
    where rf.id = p_id and ri.owner_id = p_owner for update of ri;
  if not found then raise exception 'Finding not found' using errcode = 'P0002'; end if;
  select * into f from public.research_findings where id = p_id;
  select * into neighbor from public.research_findings where inquiry_id = f.inquiry_id and
    ((p_direction = 'up' and sort_order < f.sort_order) or (p_direction = 'down' and sort_order > f.sort_order))
    order by case when p_direction = 'up' then -sort_order else sort_order end limit 1;
  if found then
    update public.research_findings set sort_order = neighbor.sort_order where id = f.id;
    update public.research_findings set sort_order = f.sort_order where id = neighbor.id;
  end if;
end $$;
revoke all on function public.move_research_finding(uuid,uuid,text) from public, anon, authenticated;
grant execute on function public.move_research_finding(uuid,uuid,text) to service_role;
